### ISSUE TITLE
Version 2.1 gives "Error making snapshot" in Blender 2.91

### ISSUE THREAD

**Issue by scpedicini** [SrFidelis/psl-snapshot#1]
I can't get this script running, unfortunately v2.1 constantly gives "Error making snapshot" in latest version of Blender (2.91) even on the simplest of animations.

bpy.ops.object.select_pattern(pattern="Cube.001", extend=False)
bpy.ops.object.make_snapshot()
Error making snapshot

**Comment by SrFidelis** [comment]
Sorry, maybe there was a problem with the communication and the explanation of how the tool works.

This is because the mesh is probably not selectable.
For it to work properly, **the mesh needs to be selectable**.
